# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 23 * * *
    
  
jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Check out codes
      uses: actions/checkout@v2
    
    - name: Set up Python 2.x
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Install Chrome
      run: sudo bash install_chrome.sh
    
    - name: Run Script
      env:
        UID: ${{ secrets.UID}}
        PASSWD: ${{ secrets.PASSWD}}
        PUSH_KEY: ${{secrets.PUSH_KEY}}
      run: python fucker.py
